### ISSUE TITLE
Error creating models with i18n fields

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/reproducible-tinynews-content-api#15]
I'm trying to create an `Author` with a few fields typed as `i18nstring()` (model) and `I18NStringValue` / `I18NStringValueInput` (graphql schema), but it errors:

```
{
  "errors": [
    {
      "message": "Object(...) is not a function",
      "path": [
        "authors",
        "createAuthor"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "serviceName": "API_TINYNEWS_MODELS",
        "query": "mutation($data:AuthorInput!){authors{createAuthor(data:$data){data{id name{value}bio{value}title{value}photoUrl twitter slug}error{code message data}}}}",
        "variables": {
          "data": {
            "name": {
              "values": [
                {
                  "value": "Jacqui Lough",
                  "locale": "bdcdaca31349dc6bb7ab64fc9058c1d7c2b5804e7c874cd8"
                }
              ]
            },
            "title": {
              "values": [
                {
                  "value": "Staff Writer",
                  "locale": "bdcdaca31349dc6bb7ab64fc9058c1d7c2b5804e7c874cd8"
                }
              ]
            },
            "bio": {
              "values": [
                {
                  "value": "Jacqui Lough is a staff writer.",
                  "locale": "bdcdaca31349dc6bb7ab64fc9058c1d7c2b5804e7c874cd8"
                }
              ]
            },
            "twitter": "@jacqui",
            "slug": "jacqui-lough",
            "photoUrl": "http://imgur.com/photo.jpg"
          }
        },
        "exception": {
          "stacktrace": [
            "TypeError: Object(...) is not a function",
            "    at Object (/var/task/handler.js:105546:40)",
            "    at instance (/var/task/handler.js:87318:22)",
            "    at /var/task/handler.js:87386:77",
            "    at Array.forEach (<anonymous>)",
            "    at baseFn.construct (/var/task/handler.js:87384:38)",
            "    at new baseFn (/var/task/handler.js:87374:14)",
            "    at /var/task/handler.js:103179:17",
            "    at /var/task/handler.js:98747:16",
            "    at field.resolve (/var/task/handler.js:36978:26)",
            "    at field.resolve (/var/task/handler.js:57676:26)"
          ]
        }
      }
    }
  ],
  "data": {
    "authors": {
      "createAuthor": null
    }
  }
}

```

**Comment by jacqui** [comment]
Figured it out!

I was using the wrong `context` which just sounds like a terrible joke but is, in fact, what was going wrong.

See the `author.model.ts` and `Author.ts` for the commodo and graphql correct setup.
