### ISSUE TITLE
Weird bug listing categories

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/reproducible-tinynews-content-api#16]
```graphql
{
  categories	{
    listCategories {
      data {
        id
        title {
          values {
            value
          }
        }
        slug
      }
    }
  }
}
```

or 

```graphql
{
  categories	{
    listCategories {
      data {
        id
        title {
            value
        }
        slug
      }
    }
  }
}
```

both result in this error:

```
{
  "errors": [
    {
      "message": "Cannot use 'in' operator to search for 'values' in World",
      "path": [
        "categories",
        "listCategories"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "serviceName": "API_TINYNEWS_MODELS",
        "query": "{categories{listCategories{data{id title{values{value}}slug}}}}",
        "variables": {},
        "exception": {
          "stacktrace": [
            "TypeError: Cannot use 'in' operator to search for 'values' in World",
            "    at FieldsStorageAdapter.fromStorage (/var/task/handler.js:95318:16)",
            "    at Array.FieldsStorageAdapter.fields.fields (/var/task/handler.js:95263:20)",
            "    at FieldsStorageAdapter.fromStorage (/var/task/handler.js:95325:53)",
            "    at baseFn.populateFromStorage (/var/task/handler.js:93159:55)",
            "    at Function.find (/var/task/handler.js:93347:29)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "categories": {
      "listCategories": null
    }
  }
}
```

**Comment by jacqui** [comment]
Pretty sure this is because of older data that fit in with earlier versions of the category model (without i18n). I'm currently relaunching the entire api stack - with a fresh mongodb this time, because I relaunched it once to try to address this bug using the same db and got the exact same error :o #themoreyouknow

**Comment by jacqui** [comment]
Yep, can confirm this was due to old, improperly formatted data. I can query categories in the new db using either `title { values { value } }` or `title { value }` with no problem.
