### ISSUE TITLE
Prevent duplicate articles

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/reproducible-tinynews-content-api#28]
Should we prevent articles being created with slugs that are already used? Seems to me that we should have a unique constraint on article slugs, or perhaps article slug + category slug? Only one article can be served by a URL (`/{category.slug}/{article.slug}`)

https://github.com/news-catalyst/google-app-scripts/issues/96

**Comment by jacqui** [comment]
Actually, I made articles unique by slug as well - slug is more straight forward to do this by as it doesn't require a locale. We can revisit doing this on the headline in the future if necessary.

**Comment by jacqui** [comment]
This is proving problematic :( 

I'm logging what I did (textbook fwiw) and the error so I can try this again in the future. I don't think this is holding us up.

```graphql
mutation CreateArticle($data: ArticleInput!) {
  articles { 
    createArticle(data: $data) {
      data {
        id
        headline {
          values {
            value
          }
        }
      }
    }
  }
}
```

**variables:**

```
{
  "data": {
    "headline": {
      "values": [
        {
          "value": "Another API",
          "locale": "5f76c560c90d6f0008819fc2"
        }
      ]
    }
  }
}
```

error:

```
{
  "errors": [
    {
      "message": "Object(...) is not a function",
      "path": [
        "articles",
        "createArticle"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "serviceName": "API_TINYNEWS_MODELS",
        "query": "mutation($data:ArticleInput!){articles{createArticle(data:$data){data{id headline{values{value}}}}}}",
        "variables": {
          "data": {
            "headline": {
              "values": [
                {
                  "value": "Another API",
                  "locale": "5f76c560c90d6f0008819fc2"
                }
              ]
            }
          }
        },
        "exception": {
          "stacktrace": [
            "TypeError: Object(...) is not a function",
            "    at Object (/var/task/handler.js:105707:50)",
            "    at instance (/var/task/handler.js:87377:22)",
            "    at /var/task/handler.js:87445:77",
            "    at Array.forEach (<anonymous>)",
            "    at baseFn.construct (/var/task/handler.js:87443:38)",
            "    at new baseFn (/var/task/handler.js:87433:14)",
            "    at /var/task/handler.js:103374:17",
            "    at /var/task/handler.js:98806:16",
            "    at field.resolve (/var/task/handler.js:36920:26)",
            "    at field.resolve (/var/task/handler.js:57735:26)"
          ]
        }
      }
    }
  ],
  "data": {
    "articles": {
      "createArticle": null
    }
  }
}
```

article.model.ts:

```
// @ts-ignore
import { withFields, withHooks, withName, string, datetime, boolean, ref } from "@webiny/commodo";
import { flow } from "lodash";
import { i18nString } from "@webiny/api-i18n/fields";

export default ({ context, createBase }) => {
    const Article: any = flow(
        withName("Article"),
        withFields(() => ({
            headline: i18nString({ context }),
            content: i18nString({ context }),
            authorSlugs: string(),
            customByline: string(),
            slug: string(),
            searchTitle: i18nString({ context }),
            searchDescription: i18nString({ context }),
            twitterTitle: i18nString({ context }),
            twitterDescription: i18nString({ context }),
            facebookTitle: i18nString({ context }),
            facebookDescription: i18nString({ context }),
            authors: ref({
                list: true,
                instanceOf: context.models.Author
            }),
            category: ref({
                list: false,
                instanceOf: context.models.Category
            }),
            tags: ref({
                list: true,
                instanceOf: context.models.Tag
            }),
            firstPublishedOn: datetime(),
            lastPublishedOn: datetime(),
            published: boolean({ value: false })
        })),
        withHooks({
            async beforeCreate() {
                const existingArticle = await Article.findOne({ query: { slug: this.slug } });
                if (existingArticle) {
                    throw Error(`Article with slug "${this.slug}" already exists.`);
                }
            },
        })
    )(createBase());
    return Article;
};
```

**Comment by jacqui** [comment]
this is now confirmed done, I just forgot to close the issue.
